version: '3.8'
services:
  bot:
    build: 
      context: ./bot
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_REPL_USER: ${DB_REPL_USER}
      DB_REPL_PASSWORD: ${DB_REPL_PASSWORD}
      DB_REPL_HOST: ${DB_REPL_HOST}
      DB_REPL_PORT: ${DB_REPL_PORT}
    depends_on:
      - db_host
    volumes:
      - ./logs:/app/logs
    networks:
      - default

  db_host:
    build: 
      context: ./db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust\nhost replication ${DB_REPL_USER} 0.0.0.0/0 trust"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./logs:/var/log/postgresql
    networks:
      - default

  db_repl_host:
    build: 
      context: ./db_repl
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_REPL_USER}
      PGPASSWORD: ${DB_REPL_PASSWORD}
    depends_on:
      - db_host
      - bot
    volumes:
      - ./db_repl/replication.sh:/docker-entrypoint-initdb.d/replication.sh
    networks:
      - default

networks:
  default:
    driver: bridge