version: '3.8'
services:
  bot:
    build: 
      context: .
    environment:
      DB_USER: db_user
      DB_PASSWORD: pass
      DB_HOST: db_host
      DB_PORT: 5432
      DB_DATABASE: bot
      DB_REPL_USER: db_repl
      DB_REPL_PASSWORD: pass
      DB_REPL_HOST: db_repl_host
      DB_REPL_PORT: 5432
    depends_on:
      - db_host
    volumes:
      - ./logs:/app/logs
    networks:
      - default

  db_host:
    build: 
      context: .
      dockerfile: ./Postgres
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./logs:/var/lib/postgresql/data/log
    networks:
      - default

  db_repl_host:
    build: 
      context: .
      dockerfile: ./Replication
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: db_repl_user
      POSTGRES_PASSWORD: pass
    depends_on:
      - db_host
    volumes:
      - ./db/replication.sh:/docker-entrypoint-initdb.d/replication.sh
    networks:
      - default

networks:
  default:
    driver: bridge