bot:
  hosts:
    host_bot:
      ansible_host: 192.168.32.151
      ansible_user: ansible
      ansible_password: ansible
    host_db:
      ansible_host: 192.168.32.147
      ansible_user: ansible
      ansible_password: ansible
    host_replication:
      ansible_host: 192.168.32.145
      ansible_user: ansible
      ansible_password: ansible